/** A platform/translation language option. `code` matches backend language
 * codes and a shipped UI dictionary in `src/lib/i18n/locales/`. `label` is the
 * language's own endonym (native name) so speakers recognize it in the picker. */
export interface Language {
  code: string;
  label: string;
}

/**
 * The full platform-language catalog: every Google Cloud Translation v2/NMT
 * target language, each with a complete static UI dictionary (exact English key
 * parity, enforced by tsc + scripts/validate-i18n.mjs). No supported language
 * falls back to English; English is only the emergency fallback for unknown or
 * invalid codes. Lower-resource locales are shipped in full and flagged for
 * native review via QA_REVIEW_LOCALES in src/lib/i18n/index.ts.
 */
export const LANGUAGES: Language[] = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
  { code: "fr", label: "Français" },
  { code: "de", label: "Deutsch" },
  { code: "it", label: "Italiano" },
  { code: "pt", label: "Português" },
  { code: "pt-BR", label: "Português (Brasil)" },
  { code: "nl", label: "Nederlands" },
  { code: "sv", label: "Svenska" },
  { code: "da", label: "Dansk" },
  { code: "no", label: "Norsk" },
  { code: "is", label: "Íslenska" },
  { code: "af", label: "Afrikaans" },
  { code: "ru", label: "Русский" },
  { code: "uk", label: "Українська" },
  { code: "be", label: "Беларуская" },
  { code: "pl", label: "Polski" },
  { code: "cs", label: "Čeština" },
  { code: "sk", label: "Slovenčina" },
  { code: "sl", label: "Slovenščina" },
  { code: "hr", label: "Hrvatski" },
  { code: "sr", label: "Српски" },
  { code: "bg", label: "Български" },
  { code: "mk", label: "Македонски" },
  { code: "lt", label: "Lietuvių" },
  { code: "lv", label: "Latviešu" },
  { code: "et", label: "Eesti" },
  { code: "el", label: "Ελληνικά" },
  { code: "hu", label: "Magyar" },
  { code: "fi", label: "Suomi" },
  { code: "ro", label: "Română" },
  { code: "ca", label: "Català" },
  { code: "gl", label: "Galego" },
  { code: "eu", label: "Euskara" },
  { code: "ga", label: "Gaeilge" },
  { code: "cy", label: "Cymraeg" },
  { code: "sq", label: "Shqip" },
  { code: "tr", label: "Türkçe" },
  { code: "az", label: "Azərbaycan" },
  { code: "kk", label: "Қазақ тілі" },
  { code: "ky", label: "Кыргызча" },
  { code: "uz", label: "Oʻzbekcha" },
  { code: "hy", label: "Հայերեն" },
  { code: "ka", label: "ქართული" },
  { code: "ar", label: "العربية" },
  { code: "he", label: "עברית" },
  { code: "fa", label: "فارسی" },
  { code: "ur", label: "اردو" },
  { code: "hi", label: "हिन्दी" },
  { code: "bn", label: "বাংলা" },
  { code: "pa", label: "ਪੰਜਾਬੀ" },
  { code: "gu", label: "ગુજરાતી" },
  { code: "mr", label: "मराठी" },
  { code: "ta", label: "தமிழ்" },
  { code: "te", label: "తెలుగు" },
  { code: "kn", label: "ಕನ್ನಡ" },
  { code: "ml", label: "മലയാളം" },
  { code: "ne", label: "नेपाली" },
  { code: "zh", label: "中文（简体）" },
  { code: "zh-TW", label: "中文（繁體）" },
  { code: "ja", label: "日本語" },
  { code: "ko", label: "한국어" },
  { code: "vi", label: "Tiếng Việt" },
  { code: "th", label: "ไทย" },
  { code: "id", label: "Bahasa Indonesia" },
  { code: "ms", label: "Bahasa Melayu" },
  { code: "fil", label: "Filipino" },
  { code: "sw", label: "Kiswahili" },
  { code: "am", label: "አማርኛ" },
  { code: "km", label: "ខ្មែរ" },
  { code: "my", label: "မြန်မာ" },
  { code: "si", label: "සිංහල" },
  { code: "lo", label: "ລາວ" },
  { code: "or", label: "ଓଡ଼ିଆ" },
  { code: "as", label: "অসমীয়া" },
  { code: "mn", label: "Монгол" },
  { code: "ku", label: "Kurdî" },
  { code: "ckb", label: "کوردیی ناوەندی" },
  { code: "ps", label: "پښتو" },
  { code: "sd", label: "سنڌي" },
  { code: "ug", label: "ئۇيغۇرچە" },
  { code: "yi", label: "ייִדיש" },
  { code: "tg", label: "Тоҷикӣ" },
  { code: "tt", label: "Татарча" },
  { code: "ba", label: "Башҡортса" },
  { code: "tk", label: "Türkmen" },
  { code: "mt", label: "Malti" },
  { code: "lb", label: "Lëtzebuergesch" },
  { code: "fy", label: "Frysk" },
  { code: "br", label: "Brezhoneg" },
  { code: "oc", label: "Occitan" },
  { code: "co", label: "Corsu" },
  { code: "gd", label: "Gàidhlig" },
  { code: "crh", label: "Qırımtatarca" },
  { code: "cv", label: "Чӑвашла" },
  { code: "ht", label: "Kreyòl Ayisyen" },
  { code: "la", label: "Latina" },
  { code: "eo", label: "Esperanto" },
  { code: "yue", label: "粵語" },
  { code: "ceb", label: "Cebuano" },
  { code: "jv", label: "Basa Jawa" },
  { code: "su", label: "Basa Sunda" },
  { code: "hmn", label: "Hmong" },
  { code: "ilo", label: "Ilokano" },
  { code: "pam", label: "Kapampangan" },
  { code: "pag", label: "Pangasinan" },
  { code: "hil", label: "Hiligaynon" },
  { code: "min", label: "Minangkabau" },
  { code: "ban", label: "Basa Bali" },
  { code: "mai", label: "मैथिली" },
  { code: "bho", label: "भोजपुरी" },
  { code: "awa", label: "अवधी" },
  { code: "doi", label: "डोगरी" },
  { code: "gom", label: "कोंकणी" },
  { code: "sa", label: "संस्कृतम्" },
  { code: "dv", label: "ދިވެހި" },
  { code: "dz", label: "རྫོང་ཁ" },
  { code: "ti", label: "ትግርኛ" },
  { code: "om", label: "Afaan Oromoo" },
  { code: "fj", label: "Na Vosa Vakaviti" },
  { code: "mi", label: "Māori" },
  { code: "sm", label: "Gagana Sāmoa" },
  { code: "haw", label: "ʻŌlelo Hawaiʻi" },
  { code: "mg", label: "Malagasy" },
  { code: "ny", label: "Chichewa" },
  { code: "sn", label: "Shona" },
  { code: "st", label: "Sesotho" },
  { code: "tn", label: "Setswana" },
  { code: "ts", label: "Xitsonga" },
  { code: "ss", label: "siSwati" },
  { code: "nr", label: "isiNdebele" },
  { code: "nso", label: "Sepedi" },
  { code: "xh", label: "isiXhosa" },
  { code: "so", label: "Soomaali" },
  { code: "ha", label: "Hausa" },
  { code: "ig", label: "Igbo" },
  { code: "yo", label: "Yorùbá" },
  { code: "rw", label: "Ikinyarwanda" },
  { code: "rn", label: "Ikirundi" },
  { code: "lg", label: "Luganda" },
  { code: "bem", label: "Ichibemba" },
  { code: "ee", label: "Eʋegbe" },
  { code: "ak", label: "Akan" },
  { code: "sg", label: "Sängö" },
  { code: "ln", label: "Lingála" },
  { code: "gn", label: "Avañe'ẽ" },
  { code: "qu", label: "Runa Simi" },
  { code: "ay", label: "Aymar aru" },
  { code: "yua", label: "Maya" },
  { code: "pap", label: "Papiamento" },
  { code: "tet", label: "Tetun" },
  { code: "scn", label: "Sicilianu" },
  { code: "lij", label: "Ligure" },
  { code: "lmo", label: "Lombard" },
  { code: "szl", label: "Ślōnski" },
  { code: "li", label: "Limburgs" },
  { code: "ltg", label: "Latgalīšu" },
  { code: "luo", label: "Dholuo" },
  { code: "bm", label: "Bamanankan" },
  { code: "ff", label: "Fulfulde" },
  { code: "gaa", label: "Gã" },
  { code: "ktu", label: "Kikongo" },
  { code: "kri", label: "Krio" },
  { code: "cnh", label: "Lai Holh" },
  { code: "lus", label: "Mizo ṭawng" },
  { code: "new", label: "नेवाः" },
  { code: "mni-Mtei", label: "ꯃꯤꯇꯩꯂꯣꯟ" },
  { code: "shn", label: "လိၵ်ႈတႆး" },
  { code: "chm", label: "Марий" },
  { code: "bua", label: "Буряад" },
  { code: "ab", label: "Аԥсшәа" },
  { code: "ace", label: "Acèh" },
  { code: "ach", label: "Acholi" },
  { code: "alz", label: "Alur" },
  { code: "din", label: "Thuɔŋjäŋ" },
  { code: "nus", label: "Thok Nath" },
  { code: "dov", label: "Dombe" },
  { code: "bew", label: "Betawi" },
  { code: "bik", label: "Bikol" },
  { code: "hrx", label: "Hunsrik" },
  { code: "mak", label: "Basa Mangkasarak" },
  { code: "btx", label: "Batak Karo" },
  { code: "bts", label: "Batak Simalungun" },
  { code: "bbc", label: "Batak Toba" },
  { code: "rom", label: "Romani" },
  { code: "bs", label: "Bosanski" },
  { code: "fr-CA", label: "Français (Canada)" },
  { code: "cgg", label: "Rukiga" },
  { code: "ms-Arab", label: "بهاس ملايو (جاوي)" },
  { code: "pa-Arab", label: "پنجابی (شاہمکھی)" },
  { code: "crs", label: "Kreol Seselwa" },
  { code: "zu", label: "isiZulu" },
];
