"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Bell, LogOut, Shield, UserRound } from "lucide-react";
import { getBlockedUsers, getProfile, logout, unblockUser, updateProfile, type BlockedUser, type ProfileResponse } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { LANGUAGES } from "@/lib/languages";
import { useLanguage } from "@/lib/language-context";

type Status = "loading" | "ready" | "error";
type Section = "account" | "privacy" | "language" | "notifications" | "session";
const FALLBACK_AVATAR = "data:image/svg+xml;utf8," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><circle cx="20" cy="20" r="20" fill="#d4d4d8"/></svg>');
const knownOrCurrent = (value: string) => LANGUAGES.some((item) => item.code === value) ? LANGUAGES : [{ code: value, label: value }, ...LANGUAGES];

export default function SettingsPage() {
  const { t, setLanguage } = useLanguage();
  const { refresh } = useAuth();
  const [status, setStatus] = useState<Status>("loading");
  const [profile, setProfile] = useState<ProfileResponse | null>(null);
  const [section, setSection] = useState<Section>("account");
  const [saving, setSaving] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [blocked, setBlocked] = useState<BlockedUser[]>([]);
  const [blockedStatus, setBlockedStatus] = useState<Status>("loading");
  const [loggingOut, setLoggingOut] = useState(false);

  const load = useCallback((signal?: AbortSignal) => { setStatus("loading"); getProfile(signal).then((value) => { setProfile(value); setStatus("ready"); }).catch((err) => { if (!(err instanceof DOMException && err.name === "AbortError")) setStatus("error"); }); }, []);
  const loadBlocked = useCallback((signal?: AbortSignal) => { setBlockedStatus("loading"); getBlockedUsers(signal).then((value) => { setBlocked(value); setBlockedStatus("ready"); }).catch((err) => { if (!(err instanceof DOMException && err.name === "AbortError")) setBlockedStatus("error"); }); }, []);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); loadBlocked(controller.signal); return () => controller.abort(); }, [load, loadBlocked]);

  const persist = async (key: string, input: Parameters<typeof updateProfile>[0], rollback: () => void, after?: (value: ProfileResponse) => void) => { if (saving) return; setSaving(key); setError(null); try { const updated = await updateProfile(input); setProfile(updated); after?.(updated); } catch { rollback(); setError(t("settings.saveError")); } finally { setSaving(null); } };
  const onUnblock = async (person: BlockedUser) => { if (saving) return; const previous = blocked; setSaving(`unblock:${person.id}`); setError(null); setBlocked((items) => items.filter((item) => item.id !== person.id)); try { await unblockUser(person.username); } catch { setBlocked(previous); setError(t("settings.saveError")); } finally { setSaving(null); } };
  const onLogout = async () => { if (loggingOut) return; setLoggingOut(true); setError(null); try { await logout(); await refresh(); } catch { setError(t("user.logoutError")); setLoggingOut(false); } };

  const nativeOptions = useMemo(() => profile ? knownOrCurrent(profile.nativeLanguage) : LANGUAGES, [profile]);
  const preferredOptions = useMemo(() => profile?.preferredLanguage ? knownOrCurrent(profile.preferredLanguage) : LANGUAGES, [profile]);
  const platformOptions = useMemo(() => profile?.platformLanguage ? knownOrCurrent(profile.platformLanguage) : LANGUAGES, [profile]);
  if (status === "loading") return <div className="mx-auto max-w-5xl space-y-4"><div className="h-8 w-40 animate-pulse rounded bg-background" />{[1, 2, 3].map((item) => <div key={item} className="h-36 animate-pulse rounded-2xl bg-surface" />)}</div>;
  if (status === "error" || !profile) return <div className="mx-auto max-w-2xl rounded-2xl border border-border bg-surface p-8 text-center shadow-sm"><p className="text-sm text-muted">{t("settings.loadError")}</p><button type="button" onClick={() => load()} className="mt-3 rounded-full bg-primary px-4 py-1.5 text-sm font-medium text-white">{t("search.tryAgain")}</button></div>;

  const nav: { id: Section; label: string }[] = [{ id: "account", label: t("settings.sectionAccount") }, { id: "privacy", label: t("settings.sectionPrivacy") }, { id: "language", label: t("settings.sectionLanguage") }, { id: "notifications", label: t("notifications.title") }, { id: "session", label: t("settings.sectionSession") }];
  return <div className="mx-auto max-w-5xl"><header className="mb-4 sm:mb-6"><h1 className="text-xl font-bold tracking-tight text-foreground sm:text-2xl">{t("navigation.settings")}</h1><p className="mt-1 text-sm text-muted">{t("settings.subtitle")}</p></header><div className="flex flex-col gap-4 md:flex-row md:items-start md:gap-5"><nav aria-label={t("navigation.settings")} className="grid shrink-0 grid-cols-2 gap-1 rounded-xl border border-border bg-surface p-1 md:flex md:w-52 md:flex-col">{nav.map((item) => <button key={item.id} type="button" onClick={() => setSection(item.id)} aria-current={section === item.id ? "page" : undefined} className={`flex min-h-11 min-w-0 items-center rounded-lg px-3 py-2 text-start text-sm font-medium leading-tight break-words transition-colors md:min-h-0 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary ${section === item.id ? "bg-primary-soft text-primary" : "text-muted hover:bg-background hover:text-foreground"}`}><span className="min-w-0 hyphens-auto break-words">{item.label}</span></button>)}</nav><main className="min-w-0 flex-1 rounded-2xl border border-border bg-surface p-4 shadow-sm sm:p-6">{error ? <p className="mb-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p> : null}
    {section === "account" ? <section><SectionTitle icon={<UserRound className="h-5 w-5" />} title={t("settings.sectionAccount")} description={t("settings.sectionAccountDescription")} /><div className="mt-5 flex flex-col gap-3 rounded-xl border border-border bg-background p-4 sm:flex-row sm:items-center sm:justify-between sm:gap-4"><div className="flex min-w-0 items-center gap-3"><Image src={profile.avatarUrl ?? FALLBACK_AVATAR} alt="" width={48} height={48} unoptimized={Boolean(profile.avatarUrl)} className="h-12 w-12 shrink-0 rounded-full object-cover" /><p className="min-w-0 break-words text-base font-semibold text-foreground">{profile.displayName}</p></div><Link href="/profile/edit" className="flex h-11 shrink-0 items-center justify-center rounded-full border border-border px-4 text-sm font-medium text-foreground transition-colors hover:bg-surface focus:outline-none focus-visible:ring-2 focus-visible:ring-primary sm:h-10">{t("profile.edit")}</Link></div></section> : null}
    {section === "privacy" ? <section><SectionTitle icon={<Shield className="h-5 w-5" />} title={t("settings.sectionPrivacy")} description={t("settings.sectionPrivacyDescription")} /><div className="mt-5 space-y-4"><Toggle checked={profile.isPrivate} disabled={saving !== null} label={t("settings.privateAccount")} description={t("settings.privateAccountDescription")} onChange={(next) => { const previous = profile.isPrivate; setProfile({ ...profile, isPrivate: next }); void persist("private", { isPrivate: next }, () => setProfile((current) => current ? { ...current, isPrivate: previous } : current)); }} />{profile.isPrivate ? <Link href="/profile?followRequests=1" className="block rounded-xl border border-border bg-background p-4 text-sm font-medium text-primary transition-colors hover:bg-surface focus:outline-none focus-visible:ring-2 focus-visible:ring-primary">{t("profile.followRequests")}</Link> : null}<BlockedPeople t={t} items={blocked} status={blockedStatus} saving={saving} onRetry={() => loadBlocked()} onUnblock={onUnblock} /></div></section> : null}
    {section === "language" ? <section><SectionTitle title={t("settings.sectionLanguage")} description={t("settings.sectionLanguageDescription")} /><div className="mt-5 space-y-4"><SettingSelect label={t("settings.platformLanguage")} description={t("settings.platformLanguageDescription")} value={profile.platformLanguage ?? ""} options={platformOptions} disabled={saving !== null} onChange={(next) => { const previous = profile.platformLanguage; setProfile({ ...profile, platformLanguage: next }); void persist("platform", { platformLanguage: next }, () => setProfile((current) => current ? { ...current, platformLanguage: previous } : current), (updated) => setLanguage(updated.platformLanguage)); }} /><SettingSelect label={t("profile.nativeLanguage")} description={t("settings.nativeLanguageDescription")} value={profile.nativeLanguage} options={nativeOptions} disabled={saving !== null} onChange={(next) => { const previous = profile.nativeLanguage; setProfile({ ...profile, nativeLanguage: next }); void persist("native", { nativeLanguage: next }, () => setProfile((current) => current ? { ...current, nativeLanguage: previous } : current)); }} /><SettingSelect label={t("settings.preferredLanguage")} description={t("settings.preferredLanguageDescription")} value={profile.preferredLanguage ?? ""} options={preferredOptions} nativeLabel={t("settings.useNativeLanguage")} disabled={saving !== null} onChange={(next) => { const previous = profile.preferredLanguage; setProfile({ ...profile, preferredLanguage: next || null }); void persist("preferred", { preferredLanguage: next || null }, () => setProfile((current) => current ? { ...current, preferredLanguage: previous } : current)); }} /><Toggle checked={profile.autoTranslateEnabled} disabled={saving !== null} label={t("settings.autoTranslate")} description={t("settings.autoTranslateDescription")} onChange={(next) => { const previous = profile.autoTranslateEnabled; setProfile({ ...profile, autoTranslateEnabled: next }); void persist("auto", { autoTranslateEnabled: next }, () => setProfile((current) => current ? { ...current, autoTranslateEnabled: previous } : current)); }} /></div></section> : null}
    {section === "notifications" ? <section><SectionTitle icon={<Bell className="h-5 w-5" />} title={t("notifications.title")} description={t("settings.notificationsDescription")} /><Link href="/notifications" className="mt-5 inline-flex rounded-full bg-primary px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-primary-hover focus:outline-none focus-visible:ring-2 focus-visible:ring-primary">{t("notifications.title")}</Link></section> : null}
    {section === "session" ? <section><SectionTitle icon={<LogOut className="h-5 w-5" />} title={t("settings.sectionSession")} description={t("settings.sectionSessionDescription")} /><button type="button" onClick={() => void onLogout()} disabled={loggingOut} className="mt-5 inline-flex rounded-full border border-red-200 px-4 py-2 text-sm font-medium text-red-600 transition-colors hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-50">{loggingOut ? t("user.loggingOut") : t("user.logout")}</button></section> : null}
  </main></div></div>;
}

function SectionTitle({ title, description, icon }: { title: string; description: string; icon?: React.ReactNode }) { return <header className="flex gap-3"><span className="mt-0.5 text-primary">{icon}</span><div><h2 className="text-lg font-semibold text-foreground">{title}</h2><p className="mt-1 text-sm text-muted">{description}</p></div></header>; }
function Toggle({ checked, disabled, onChange, label, description }: { checked: boolean; disabled: boolean; onChange: (value: boolean) => void; label: string; description: string }) { return <label className="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-border bg-background p-4 has-[:disabled]:cursor-not-allowed has-[:disabled]:opacity-60"><span><span className="block text-sm font-medium text-foreground">{label}</span><span className="mt-1 block text-xs leading-5 text-muted">{description}</span></span><input type="checkbox" role="switch" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} className="mt-0.5 h-5 w-9 cursor-pointer appearance-none rounded-full bg-muted-soft transition-colors checked:bg-primary focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 disabled:cursor-not-allowed" /></label>; }
function SettingSelect({ label, description, value, options, nativeLabel, disabled, onChange }: { label: string; description: string; value: string; options: typeof LANGUAGES; nativeLabel?: string; disabled: boolean; onChange: (value: string) => void }) { return <label className="block rounded-xl border border-border bg-background p-4"><span className="block text-sm font-medium text-foreground">{label}</span><span className="mt-1 block text-xs text-muted">{description}</span><select value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} className="mt-3 h-11 w-full min-w-0 rounded-lg border border-border bg-surface px-3 text-base text-foreground sm:h-10 sm:text-sm focus:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:cursor-not-allowed disabled:opacity-60">{nativeLabel ? <option value="">{nativeLabel}</option> : null}{options.map((language) => <option key={language.code} value={language.code}>{language.label} — {language.code}</option>)}</select></label>; }
function BlockedPeople({ t, items, status, saving, onRetry, onUnblock }: { t: ReturnType<typeof useLanguage>["t"]; items: BlockedUser[]; status: Status; saving: string | null; onRetry: () => void; onUnblock: (person: BlockedUser) => void }) { return <section className="rounded-xl border border-border bg-background p-4"><h3 className="text-sm font-medium text-foreground">{t("settings.blockedPeople")}</h3>{status === "loading" ? <p className="mt-3 text-sm text-muted">{t("settings.blockedLoading")}</p> : null}{status === "error" ? <div className="mt-3 text-sm text-muted">{t("settings.blockedLoadError")} <button type="button" onClick={onRetry} className="text-primary underline">{t("search.tryAgain")}</button></div> : null}{status === "ready" && items.length === 0 ? <p className="mt-3 text-sm text-muted">{t("settings.blockedEmpty")}</p> : null}{items.length > 0 ? <ul className="mt-3 divide-y divide-border">{items.map((person) => <li key={person.id} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><Link href={`/u/${encodeURIComponent(person.username)}`} className="shrink-0"><Image src={person.avatarUrl ?? FALLBACK_AVATAR} alt={person.displayName} width={40} height={40} unoptimized={Boolean(person.avatarUrl)} className="h-10 w-10 rounded-full object-cover" /></Link><Link href={`/u/${encodeURIComponent(person.username)}`} className="min-w-0 flex-1 hover:underline"><span className="block truncate text-sm font-medium text-foreground">{person.displayName}</span><span className="block truncate text-xs text-muted">@{person.username}</span></Link><button type="button" disabled={saving !== null} onClick={() => void onUnblock(person)} className="h-9 shrink-0 rounded-full border border-border px-3 text-xs font-medium text-foreground hover:bg-surface disabled:opacity-50">{t("profile.unblock")}</button></li>)}</ul> : null}</section>; }
